using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using AiEstimator.Models;

namespace AiEstimator.Services;

public class PdfExportService
{
    public byte[] GenerateEstimationPdf(GameEstimationResult estimation, string fileName)
    {
        QuestPDF.Settings.License = LicenseType.Community;
        
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                
                page.Header().Element(ComposeHeader);
                page.Content().Element(content => ComposeContent(content, estimation, fileName));
                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by Game Dev AI Estimator - ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
        });

        return document.GeneratePdf();
    }

    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text("Game Development Estimation").FontSize(24).Bold().FontColor(Colors.Blue.Medium);
                column.Item().Text("Unity Engine Project").FontSize(12).FontColor(Colors.Grey.Medium);
            });

            row.ConstantItem(100).AlignRight().Text($"{DateTime.Now:MMM dd, yyyy}").FontSize(10).FontColor(Colors.Grey.Medium);
        });
    }

    private void ComposeContent(IContainer container, GameEstimationResult estimation, string fileName)
    {
        container.PaddingVertical(20).Column(column =>
        {
            column.Spacing(15);

            column.Item().Text($"Document: {fileName}").FontSize(11).FontColor(Colors.Grey.Darken2);
            
            column.Item().PaddingTop(10).Element(c => ComposeProjectSummary(c, estimation));
            
            column.Item().PaddingTop(10).Element(c => ComposeTotals(c, estimation));
            
            column.Item().PaddingTop(20).Element(c => ComposeFeatureTable(c, estimation));
        });
    }

    private void ComposeProjectSummary(IContainer container, GameEstimationResult estimation)
    {
        container.Background(Colors.Blue.Lighten4).Padding(15).Column(column =>
        {
            column.Item().Text("Project Overview").FontSize(14).Bold().FontColor(Colors.Blue.Medium);
            column.Item().PaddingTop(5).Text(estimation.ProjectSummary).FontSize(10).LineHeight(1.5f);
        });
    }

    private void ComposeTotals(IContainer container, GameEstimationResult estimation)
    {
        container.Row(row =>
        {
            row.RelativeItem().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(column =>
            {
                column.Item().AlignCenter().Text("💻 Development").FontSize(11).Bold();
                column.Item().AlignCenter().PaddingTop(5).Text($"{estimation.TotalDevHours} hrs").FontSize(16).Bold().FontColor(Colors.Blue.Medium);
                column.Item().AlignCenter().Text($"~{Math.Ceiling(estimation.TotalDevHours / 8.0)} days").FontSize(9).FontColor(Colors.Grey.Medium);
            });

            row.Spacing(10);

            row.RelativeItem().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(column =>
            {
                column.Item().AlignCenter().Text("🎨 Art & Design").FontSize(11).Bold();
                column.Item().AlignCenter().PaddingTop(5).Text($"{estimation.TotalArtHours} hrs").FontSize(16).Bold().FontColor(Colors.Blue.Medium);
                column.Item().AlignCenter().Text($"~{Math.Ceiling(estimation.TotalArtHours / 8.0)} days").FontSize(9).FontColor(Colors.Grey.Medium);
            });

            row.Spacing(10);

            row.RelativeItem().Background(Colors.Blue.Medium).Padding(10).Column(column =>
            {
                column.Item().AlignCenter().Text("⏱️ Total Project").FontSize(11).Bold().FontColor(Colors.White);
                column.Item().AlignCenter().PaddingTop(5).Text($"{estimation.TotalHours} hrs").FontSize(16).Bold().FontColor(Colors.White);
                column.Item().AlignCenter().Text($"~{Math.Ceiling(estimation.TotalHours / 8.0)} days").FontSize(9).FontColor(Colors.Grey.Lighten3);
            });
        });
    }

    private void ComposeFeatureTable(IContainer container, GameEstimationResult estimation)
    {
        container.Column(column =>
        {
            column.Item().Text("Feature Breakdown").FontSize(14).Bold().FontColor(Colors.Blue.Medium);
            
            column.Item().PaddingTop(10).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(3);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(3);
                });

                table.Header(header =>
                {
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).Text("Feature").FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).Text("Description").FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).Text("Complexity").FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).AlignCenter().Text("Dev (hrs)").FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).AlignCenter().Text("Art (hrs)").FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).AlignCenter().Text("Total").FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Medium).Padding(5).Text("Notes").FontSize(9).Bold().FontColor(Colors.White);
                });

                foreach (var feature in estimation.Features)
                {
                    var totalHours = feature.DevEstimateHours + feature.ArtEstimateHours;
                    var complexityColor = feature.Complexity.ToLower() switch
                    {
                        "low" => Colors.Green.Lighten3,
                        "high" => Colors.Red.Lighten3,
                        _ => Colors.Yellow.Lighten3
                    };

                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).Text(feature.Feature).FontSize(9).Bold();
                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).Text(feature.Description).FontSize(8).LineHeight(1.3f);
                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).Background(complexityColor).AlignCenter().Text(feature.Complexity).FontSize(8).Bold();
                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).AlignCenter().Text(feature.DevEstimateHours.ToString()).FontSize(9);
                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).AlignCenter().Text(feature.ArtEstimateHours.ToString()).FontSize(9);
                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).AlignCenter().Text(totalHours.ToString()).FontSize(9).Bold().FontColor(Colors.Blue.Medium);
                    table.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5).Text(feature.Notes).FontSize(8).Italic().FontColor(Colors.Grey.Darken1);
                }
            });
        });
    }
}
